# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

index:
    path: /
    defaults: { _controller: 'App\Controller\VideoController::index' }

listing_films:    
    path: /films
    defaults: { _controller: 'App\Controller\FilmsController::index' }  
    
film_show:
  path: /films/show/{id}
  controller: App\Controller\FilmsController::show 

film_edit:
  path: /films/edit/{id}
  controller: App\Controller\FilmsController::edit   
  
  
film_remove:
  path: /films/delete/{id}
  controller: App\Controller\FilmsController::delete 
  
film_add:
  path: /films/add
  controller: App\Controller\FilmsController::add  


 
